### ISSUE TITLE
Error opening czi file

### ISSUE THREAD

**Issue by emmenlau** [bigdataviewer/SPIM_Registration#57]
With latest Fiji from 2015.06.17 I get an error opening a new czi file. From the logs:
```
Using spimdata version: 0.9-revision
Using spimreconstruction version: 2.3.8

java.lang.RuntimeException: Could not read stack size for angle 0, stopping.
	at spim.fiji.datasetmanager.LightSheetZ1MetaData.loadMetaData(LightSheetZ1MetaData.java:149)
	at spim.fiji.datasetmanager.LightSheetZ1MetaData.loadMetaData(LightSheetZ1MetaData.java:79)
	at spim.fiji.datasetmanager.LightSheetZ1.createDataset(LightSheetZ1.java:74)
	at spim.fiji.plugin.Define_Multi_View_Dataset.defineDataset(Define_Multi_View_Dataset.java:105)
	at spim.fiji.plugin.Data_Explorer.run(Data_Explorer.java:53)
	at ij.IJ.runUserPlugIn(IJ.java:199)
	at ij.IJ.runPlugIn(IJ.java:163)
	at ij.Executer.runCommand(Executer.java:131)
	at ij.Executer.run(Executer.java:64)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by StephanPreibisch** [comment]
Can you please send me the Log Window as well as the console output as well? It works for me ...

**Comment by StephanPreibisch** [comment]
It should print the entire metadata as well, I need that too to see why this is going wrong

**Comment by emmenlau** [comment]
I uploaded the logs here: http://data.marssoft.de/manual_multiview20x_beads0.52um1zu12000_fish.tar.gz

**Comment by StephanPreibisch** [comment]
Leading zeros for indicies is the problem ... great :)

**Comment by StephanPreibisch** [comment]
Fixed with commit https://github.com/bigdataviewer/SPIM_Registration/commit/4084e2152dd41ef734d772817f9c4de19481c113

Can you please try the JAR from here? http://jenkins.imagej.net/view/BigDataViewer/job/SPIM_Registration/

**Comment by emmenlau** [comment]
Yep, that works. Thanks!

**Comment by StephanPreibisch** [comment]
Cool, I will draft a new release later today or this weekend! Thanks!!

**Comment by Horkheimer** [comment]
Dear Stephan

I am still getting this error on some of my .czi datasets.

<pre><code>java.lang.RuntimeException: Could not read stack size for angle 0, stopping.
	at spim.fiji.datasetmanager.LightSheetZ1MetaData.loadMetaData(LightSheetZ1MetaData.java:162)
	at spim.fiji.datasetmanager.LightSheetZ1MetaData.loadMetaData(LightSheetZ1MetaData.java:83)
	at spim.fiji.datasetmanager.LightSheetZ1.createDataset(LightSheetZ1.java:75)
	at spim.fiji.plugin.Define_Multi_View_Dataset.defineDataset(Define_Multi_View_Dataset.java:107)
	at spim.fiji.plugin.Define_Multi_View_Dataset.run(Define_Multi_View_Dataset.java:51)
	at ij.IJ.runUserPlugIn(IJ.java:212)
	at ij.IJ.runPlugIn(IJ.java:176)
	at ij.Executer.runCommand(Executer.java:132)
	at ij.Executer.run(Executer.java:65)
	at java.lang.Thread.run(Thread.java:695)
</code></pre>

After changing to the version you posted here, the error message changes, but still it is not working. I posted the output of the Console, Log and the Metadata from the first file of the dataset [here](https://www.dropbox.com/sh/j49s1o0fcwdyta0/AACzLMQcQuTDqHA17wgFabsxa?dl=0). Please have a look.

 
Thanks a lot for your work!
